### ISSUE TITLE
Jenkins Server set up for SBA.

### ISSUE THREAD

**Issue by uwuplant** [BiscuitDevelopment/SkyblockAddons#130]
[Here c:](http://24.202.239.85:8080/job/SkyblockAddons/)
Should automatically build on every new commit. I will monitor it for the next couple days to make sure it's working fine.

**Comment by timelsass** [comment]
repository owner should make a decision as to what CI to use if needed.  I'd suggest travis since it's free for opensource projects, and integration with github takes seconds and publishes to github releases page.   This would let people download the latest build from the releases tab on github.

Also, you do realize open source means public?  When your internet gets shut down shortly, I'm sure you'll figure it out.

**Comment by ILikePlayingGames** [comment]
We ended up choosing GitHub Actions.
