### ISSUE TITLE
[Feature Request] Show the different possible recipes for enchanted items based on what you have in your inventory

### ISSUE THREAD

**Issue by Keagel** [BiscuitDevelopment/SkyblockAddons#146]
And allow us to click/shift-click to craft them automatically? For example if you have a full inventory of cobblestone it'd show you the enchanted cobblestone recipe and you'd just shift-click it to craft all your cobblestone into the enchanted version. Something like the recipe book that was added in later versions.

**Comment by DidiSkywalker** [comment]
That'd be considered a macro which is bannable on Hypixel

**Comment by Keagel** [comment]
The way I see it (and the way the recipe book feature works), the blocks are simply placed in the crafting table and it's up to you to do the crafting part. I fail to understand how it'd be considered a macro, especially since anyone playing on 1.12 has this feature, minus the custom recipes.

**Comment by ViralTaco** [comment]
I'd love a feature like this but sadly I must agree. Hypixel considers that a macro.
Reason probably is that you don't want that in PVP (not sure how making enchanted bacon would help there but who knows) 
Also, as far as I know, that feature is actually disabled since it's a 1.8 server. 
Last time I played with 1.14.4 it actually didn't show up.

**Comment by SirNapkin1334** [comment]
This is replaced by the new Quick Crafting feature. I'd recommend closing the issue as it's no longer necessary. And, as aforementioned, it's be a macro
